# Generated by Django 4.0.1 on 2022-01-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_speciality_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subject',
            table='Subject',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='Teacher',
        ),
    ]
